- hosts: all
  tasks:
    - name: Docker
      copy:
          src: "/etc/yum.repos.d/docker.repo"
          dest: "/etc/yum.repos.d/" 
    - name: Installing Docker
      package:
            name: "docker-ce-18.09.1-3.el7.x86_64"
            state: present
    - name: Starting Docker Service
      service:
            name: docker
            state: started
            enabled: yes
    - name: Install Docker SDK for python3
      command: "pip3 install docker-py"

    - name: Pull a Docker Image
      docker_image:
              name: httpd
              tag: latest
              source: pull
    
    
     
    - name: Copying the html page in the Directory
      copy:
         src: "/root/ansible/playbook/web.html"
         dest: "/usr/local/apache2/htdocs/"
    
    - name: Launching an HTTPD Container
      docker_container:
              name: httpd
              image: httpd
              state: started
              exposed_ports:
              - "80"
              ports:
              - "8888:80"

              
